version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filmfriend_next_app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - /app/src/node_modules
      - /app/src/.next
    # Environment variables for the backend will be added here later
    # For example:
    # environment:
    #   - NEXT_PUBLIC_API_BASE_URL=http://fastapi-backend:8000
    restart: always

# The postgres, redis, and pgadmin services have been removed.
# They should be managed as part of your separate FastAPI backend service.
